# The primary environment for testing. Some jobs selectively override these settings.
os: linux
arch: amd64
dist: xenial
language: python
python: "3.8"

# Only test the final merges and releases. The work-in-progress branches are tested by PR builds.
branches:
  only:
  - master
  - /^release\/.*$/
  - /^\d+\.\d+(\.\d+)?(\.?(rc|dev|pre|post)\d+)?(-\S*)?(\+\S*)?$/

# Linting is super-fast and lightweight, gives the near-instant feedback if code is wrong.
# It does not depend on the environment (services, dependencies, even the framework itself).
# Currently, most linters are optional and performed manually from time to time. This will change.
_linting: &linting
#  install: []  # no requirements.txt  # TODO: Uncomment again when pre-commit is used (saves ~15s)
  services: []  # no docker & co
  before_script: []
  script:
    - isort . --check --diff || true
    - isort examples --settings=examples --check --diff || true

# Unit-tests depend on a lightweight environment of the framework and its dependencies only, no K8s.
# Type-checking also needs the dependencies installed, but it goes first for faster failure.
_unittests: &unittests
  services: []  # no docker & co
  before_script: []
  script:
    - mypy kopf --strict --pretty
    - pytest --cov=kopf --cov-branch
  after_success:
    - coveralls || true
    - codecov --flags unit

# Realistic tests are heavy, slow, but needed even for PRs. They use real K8s of different versions.
# Coverage is not measured in these tests, as all lines will be covered anyway, even if some
# potentially buggy scenarios/edge-cases are missing -- such coverage is not trustworthy.
_integration: &realistic
  services:
    - docker
  before_script:
    - tools/install-clients.sh
    - tools/install-kubectl.sh
    - tools/install-k3d-k3s.sh
  script:
    - pytest --only-e2e

# Full-scale tests run all setups and all K8s versions (including those not supported by lightweight
# K3d/K3s in PR/branch-tests). They are too slow and too numerous for PRs, so they run by cron only.
# To run/debug in a PR, comment out the `if:` line. Uncomment it back before merging.
_nightly: &fullscale
  if: env(TRAVIS_EVENT_TYPE) == cron
  services:
    - docker
  before_script:
    - tools/install-clients.sh
    - tools/install-kubectl.sh
    - tools/install-minikube.sh
  script:
    - pytest --only-e2e

# The job matrix combines all scripts with all intended setups.
# Only one Python version is tested with all supported K8s versions: to check for API compatibility.
# Other Python versions are tested with only one K8s version: if it works for one, it works for all.
# Ordering is important: 4 heavy jobs (5m) start asap, 3 fast jobs (1+2+2 min) run sequentially,
# thus fitting into Travis's 5-job limit with the fastest possible outcome. For cron, ignore timing.
jobs:
  include:

  # Regular (daily/nightly) tests for all and old K8s versions. Very slow (8m).
  - { <<: *fullscale, env: K8S=latest CLIENT=yes }
  - { <<: *fullscale, env: K8S=latest }
  - { <<: *fullscale, env: K8S=v1.19.0 }
  - { <<: *fullscale, env: K8S=v1.18.8 }
  - { <<: *fullscale, env: K8S=v1.17.11 }
  - { <<: *fullscale, env: K8S=v1.16.14 }
  - { <<: *fullscale, env: K8S=v1.16.14 CRDAPI=v1beta1 }
  - { <<: *fullscale, env: K8S=v1.15.12 CRDAPI=v1beta1 }
  - { <<: *fullscale, env: K8S=v1.14.10 CRDAPI=v1beta1 }
  - { <<: *fullscale, env: K8S=v1.13.12 CRDAPI=v1beta1 }

  # Integration tests are slow (5-6m). Limit to 4 representative setups for faster PR feedbacks.
  - { <<: *realistic, env: K3S=latest CLIENT=yes }
  - { <<: *realistic, env: K3S=v1.18.8+k3s1 }
  - { <<: *realistic, env: K3S=v1.16.14+k3s1 }
  - { <<: *realistic, env: K3S=v1.16.14+k3s1 CRDAPI=v1beta1 }

  # Linting is super-fast and lightweight (40s), gives the near-instant feedback.
  # Unit-tests are relatively fast (2m), but no integration tests, no k8s installed.
  # This pack of jobs takes roughly 5m, which is a duration of one realistic job.
  - { <<: *linting, name: Linting and static analysis }
  - { <<: *unittests, python: "3.7" }
  - { <<: *unittests, python: "3.8" }

  fast_finish: true
  allow_failures:
    - python: "3.9-dev"

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "Rya+PxejTJQLEiLAjdwDXQu6H3PPEx0dmbj2wrfAUqi4B2ybuIfSno3GE1EQ4O41iXm7Oh5r53sCCxYjIvuXH1l5K3c8qerwTuYk5Kek60Rc04HUZnsLi9Z1mRTFQgpuJHvPU0+MJG5RMfV15aC4ondcWIeHri1TgTxmHzkQu2t2jqZ+majd75KwcnSuH1/vS/10Fkv1uQqope929io8r6scmdpOZ0hDZqXV7UG18Str6JEFuE7oFLJq1NNy7rINS/kGMU/qlObFa21VEm6bFSvxYhbvmW17vGKP5HsNvttqf5qgRvDY7d5c3glsduiDyL6a8AGNYEcCDwEA1dE9pQ7IKnBlHikfS1TuXiQjp5Rfdh61sqUQ5UJH7JHBEFOxZzwJpf3VcOx3uXq+XdSPgI+t1nzGm25OiXTo1I6LlpZdr33v3Ox5N2Fpeh/XQLSOnyMEssHQFDdI6mFfg6DNdLggBK9JCyFBArpy6QwyGcN4ul762XHdRQSkp0aRMEmavIFoBlDg9laNrgEXZJLhE56cTlre4JNxm4PeXFz0UUGBrrum7G/MSP+symzyMTJpfVbNfFKZOjPS5WneT7HiZuPyeQCbTT9kszJC6+2h40NxyByPr0zkhbTk7WjEUmD11YkLZ0UiPVtiTafe9Kks1inxZ2SOHkJ1j06Tao7C74E="
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true  # prohibit local versions not on the releases
