# See https://github.com/LiliC/travis-minikube for Travis+Minikube.
# This affects the env & before_script sections, and some functional tests.
language: python
sudo: required
dist: xenial
services:
  - docker

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_IN_STYLE=true
    - MINIKUBE_HOME=$HOME
    - MINIKUBE_VERSION=latest
  matrix:
    - KUBERNETES_VERSION=latest CLIENT=yes  # only one "yes" is enough
    - KUBERNETES_VERSION=latest CLIENT=no
    - KUBERNETES_VERSION=v1.17.11 CLIENT=no
    - KUBERNETES_VERSION=v1.16.14 CLIENT=no  # starting from 1.16, use CRD API v1.
    - KUBERNETES_VERSION=v1.16.14 CLIENT=no CRDAPI=v1beta1
    - KUBERNETES_VERSION=v1.15.12 CLIENT=no CRDAPI=v1beta1
    - KUBERNETES_VERSION=v1.14.10 CLIENT=no CRDAPI=v1beta1
    - KUBERNETES_VERSION=v1.13.12 CLIENT=no CRDAPI=v1beta1

# Only one Python version is tested with all supported K8s versions: to check for API compatibility.
# Other Python versions are tested with only one K8s version: if it works for one, it works for all.
# One look-ahead Python dev version is tested for preview, but is optional.
python:
  - "3.8"
matrix:
  include:
    - python: "3.7"
      env: KUBERNETES_VERSION=latest CLIENT=yes
    - python: "3.7"
      env: KUBERNETES_VERSION=latest CLIENT=no
    - python: "3.9-dev"
  allow_failures:
    - python: "3.9-dev"

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y conntrack  # see #334

before_script:
  - tools/minikube-for-travis.sh
  - tools/kubernetes-client.sh

script:
  - pytest --cov=kopf --cov-branch
  - coveralls || true
  - codecov --flags unit
  - pytest --only-e2e  # NB: after the coverage uploads!
  - mypy kopf --strict --pretty

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "Rya+PxejTJQLEiLAjdwDXQu6H3PPEx0dmbj2wrfAUqi4B2ybuIfSno3GE1EQ4O41iXm7Oh5r53sCCxYjIvuXH1l5K3c8qerwTuYk5Kek60Rc04HUZnsLi9Z1mRTFQgpuJHvPU0+MJG5RMfV15aC4ondcWIeHri1TgTxmHzkQu2t2jqZ+majd75KwcnSuH1/vS/10Fkv1uQqope929io8r6scmdpOZ0hDZqXV7UG18Str6JEFuE7oFLJq1NNy7rINS/kGMU/qlObFa21VEm6bFSvxYhbvmW17vGKP5HsNvttqf5qgRvDY7d5c3glsduiDyL6a8AGNYEcCDwEA1dE9pQ7IKnBlHikfS1TuXiQjp5Rfdh61sqUQ5UJH7JHBEFOxZzwJpf3VcOx3uXq+XdSPgI+t1nzGm25OiXTo1I6LlpZdr33v3Ox5N2Fpeh/XQLSOnyMEssHQFDdI6mFfg6DNdLggBK9JCyFBArpy6QwyGcN4ul762XHdRQSkp0aRMEmavIFoBlDg9laNrgEXZJLhE56cTlre4JNxm4PeXFz0UUGBrrum7G/MSP+symzyMTJpfVbNfFKZOjPS5WneT7HiZuPyeQCbTT9kszJC6+2h40NxyByPr0zkhbTk7WjEUmD11YkLZ0UiPVtiTafe9Kks1inxZ2SOHkJ1j06Tao7C74E="
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true  # prohibit local versions not on the releases
